# Generated by Django 4.0.6 on 2022-12-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cur_ID', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(null=True)),
                ('Cur_Abbreviation', models.CharField(max_length=3, null=True)),
                ('Cur_Scale', models.IntegerField(default=1)),
                ('Cur_Name', models.CharField(max_length=255, null=True)),
                ('Cur_OfficialRate', models.FloatField(null=True)),
            ],
        ),
    ]
